service: ubd-bot

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-2
  stage: ${self:custom.NODE_ENV}
  environment:
    NODE_ENV: ${self:custom.NODE_ENV}

custom:
  NODE_ENV: ${env:NODE_ENV, 'development'}

plugins:
  - serverless-offline

package:
  exclude:
    - .git/**
    - scripts/**
    - .vscode/**
    - schemas/**
    - .gitignore
    - .nvmrc
    - README.md
    - .env.example


functions:
  tweetRandomQuote:
    handler: src/handler.tweetRandomQuote
    events:
      - schedule: cron(0 0,12 * * ? *)
  collectDailyBoxOffice:
    handler: src/handler.collectDailyBoxOffice
    events:
      - schedule: cron(0 0 * * ? *)
  replyToMention:
    handler: src/handler.replyToMention
    events:
      - http:
          path: mentions
          method: post
          cors: true
  crc:
    handler: src/handler.crc
    events:
      - schedule: rate(15 minutes)
      - http:
          path: mentions
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                crc_token: true
