service: ubd-bot

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-2
  stage: ${self:custom.env.UBD_BOT_ENV}
  environment:
    UBD_BOT_ENV: ${self:custom.env.UBD_BOT_ENV}
    TWITTER_CONSUMER_KEY: ${self:custom.env.TWITTER_CONSUMER_KEY}
    TWITTER_CONSUMER_SECRET: ${self:custom.env.TWITTER_CONSUMER_SECRET}
    TWITTER_ACCESS_TOKEN_KEY: ${self:custom.env.TWITTER_ACCESS_TOKEN_KEY}
    TWITTER_ACCESS_TOKEN_SECRET: ${self:custom.env.TWITTER_ACCESS_TOKEN_SECRET}
    MONGO_CONNECTION_STRING: ${self:custom.env.MONGO_CONNECTION_STRING}
    KMDB_SERVICE_KEY: ${self:custom.env.KMDB_SERVICE_KEY}
    KMDB_HOST: ${self:custom.env.KMDB_HOST}
    KOFIC_API_KEY: ${self:custom.env.KOFIC_API_KEY}
    KOFIC_API_BASE_URL: ${self:custom.env.KOFIC_API_BASE_URL}
    TWITTER_BOT_USERNAME: ${self:custom.env.TWITTER_BOT_USERNAME}

custom:
  env: ${file(./.env.json)}

plugins:
  - serverless-offline

package:
  exclude:
    - .git/**
    - scripts/**
    - .vscode/**
    - schemas/**
    - .gitignore
    - .nvmrc
    - README.md


functions:
  tweetRandomQuote:
    handler: src/handler.tweetRandomQuote
    events:
      - schedule: cron(0 0,12 * * *)
  replyToMention:
    handler: src/handler.replyToMention
    events:
      - http:
          path: mentions
          method: post
          cors: true
  crc:
    handler: src/handler.crc
    events:
      - schedule: rate(15 minutes)
      - http:
          path: mentions
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                crc_token: true
